include:
  - project: infra/ci-templates
    file: "commit.yml"
    ref: master
  - project: infra/ci-templates
    file: "python.yml"
    ref: master
    inputs:
      srcfolder: "servc"
  - project: infra/ci-templates
    file: "python_pypi.yml"
    ref: master

stages:
  - lint
  - test
  - tag
  - release
