version: "3.8"

services:
  python:
    image: mcr.microsoft.com/vscode/devcontainers/python
    volumes:
      - .:/workspace:cached
      - ../docs:/workspace/servc-docs
      - /Users/yusuf/Documents/bin/format:/usr/local/bin/format
    command: sleep infinity
    environment:
      START_SCRIPT: /workspace/main.py
      CACHE_URL: redis://redis:6379/0
      BUS_URL: amqp://rabbitmq:rabbitmq@rabbitmq/
    links:
      - rabbitmq
      - redis

  redis:
    image: redis
    restart: unless-stopped
    expose:
      - "6379"
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"