[project]
name = "{{PROJECT_NAME}}"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "pika>=1.3.2",
    "pyyaml>=6.0.3",
    "redis>=6.4.0",
    "servc>=1.11.11",
    "simplejson>=3.20.2",
]
