name: 'Package Publish'
on: 
  - push

jobs: 
  packagepublish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build twine
      
      - name: Setup Version
        if: github.ref_name == 'main'
        run: |
          TAG=$(git tag --points-at HEAD)
          sed -i "s/version = .*/version = \"$TAG\"/g" pyproject.toml

      - name: Build package
        run: |
          python -m build        

      - name: Publish package
        if: github.ref_name == 'main'
        run: |
          python -m twine upload dist/* --non-interactive