name: 'Package Publish'
on: 
  - push

jobs: 
  packagepublish:
    runs-on: ubuntu-latest
    steps:
      - uses: https://git.yusufali.ca/actions/commit@main

      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build twine        

      - name: Get Current Version
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.1

      - name: Setup Version
        env:
          TAG: ${{ steps.previoustag.outputs.tag }}
        run: |
          sed -i "s/version = .*/version = \"$TAG\"/g" pyproject.toml
          cat pyproject.toml        

      - name: Build package
        run: python -m build

      - name: Publish package
        if: github.ref_name == 'main'
        run: |
          python -m twine upload dist/* --non-interactive -u__token__ -p${{ secrets.PYPI_TOKEN }}
