name: 'Changelong'
on: 
  - push

jobs: 
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: https://git.yusufali.ca/actions/commit@main

      - uses: https://git.yusufali.ca/actions/pythonpip@main
        with:
          pypiptoken: ${{ secrets.PYPI_TOKEN }}